USE [C:\USERS\LI XIAN\DOCUMENTS\GRADE SYSTEM\GRADING-SYSTEM\GRADING_SYSTEM\GRADING_SYSTEM.MDF];
GO

ALTER USER Checker WITH LOGIN = LoginChecker
ALTER USER SuperAdmin WITH LOGIN = SuperAdmin
ALTER USER AssistantTeacher WITH LOGIN = AssistantTeacher
ALTER USER Registrar WITH LOGIN = Registrar;
ALTER USER Teacher WITH LOGIN = Teacher